### ISSUE TITLE
Monsters spawn outside of walls. Can't be killed.

### ISSUE THREAD

**Issue by mechanator** [argonatorUberTF/Uber-Team-Fortress#12]
There are two issues here:
1. In survival mode there are extra monsters spawned beyond the .ent or .bsp map definitions randomly. However they are sometimes spawning outside of the map or in walls.

The walkmove() command for the monsters should detect this and remove the monster and the spawn for it.  However the detection code needs work.  The players don't get the frag kill for it, but the monster count total should go down.

2. When monsters are spawned, sometimes on a sloped surface and halfway out of the map the droptofloor() command bugs and the monsters fall out of map. 
The loop for detecting this is not 100% right and sometimes the monsters are in the sky or below the floor.  One possible fix is to spawn them further above the "floor" of the map and they can drop to walk off towards their target. However that doesn't cover flying type of monsters.

**Comment by argonatorUberTF** [comment]
Fix most of the ai monsters spawning outside of the map or doing walkmonster into walls.
the problem was in ai.pqc and in spawnfunc.
Still there are some triggers that do not teleport monsters from hidden boxes onto the scene.
it's up to a map debugger to add the correct tfgoal and triggers. Especially doc maps.
The cyberdemon on Doc based maps are making a non ai call and don't react or shoot back. fix the maps doc.
